### ISSUE TITLE
Only the DEBUG release works reliably

### ISSUE THREAD

**Issue by KimBrusevold** [rgutmann/battleground-alpha-game#1]
Would try to see if I could help you out.

I downloaded the project and I can test the game from the engine and it seems to play well. 
I can also export the project to windows. I don't specify any release flag, but it seems from documentation a debug release is opt-in (https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_projects.html)

Are there any ways to provoke a crash when playing the release build? 
(I am using Godot v. 3.2.3)

**Comment by rgutmann** [comment]
Hey Kim, thank you for your interest! :)

From my experience the crash happens mostly inside of the first 2-3 waves/rounds, but I don't know of a specific way to reproduce it. I'm using the same Godot version btw.

**Comment by rgutmann** [comment]
![grafik](https://user-images.githubusercontent.com/34044509/110909548-7d4f5a80-8310-11eb-82c7-f594e1b5d64f.png)

The release build is nothing more than disabling this flag inside of the export save file dialog (also 3.2.3 export template).

**Comment by KimBrusevold** [comment]
Good! I did some testing, gave myself unlimited health to test things a bit more controlled (just modified the func **hit()** in **Tank.gd**. I only decrease health if enemy. Here are the first line of the func:


func hit(projectile)
   if health <= 0 || !get_parent().is_running():
		return
	if is_enemy:
		health = health - projectile.get_impact()	


One way i reliably made the game crash was to shoot and hit an already exploded enemy tank. If I only shot an enemy so much that it exploded, and did not hit it again, the game seems to play as normal. 

Need to do more testing, if you test the same thing let me know if you get the same results ;)

**Comment by rgutmann** [comment]
Wow - great. That's a good starting point and a nice way to approach this kind of problems. I'll try that as well! :)

**Comment by rgutmann** [comment]
I've added your strategy as a debug cheat option to the game. Usage destroys the score ofc. :)

**Comment by rgutmann** [comment]
Oh, and yes, I've had the same results: release crashes when remaining hulls are destroyed while the debug has no problem with that! 👍

**Comment by rgutmann** [comment]
I think it may be related to the queue_free() call, which I've considered safe until now.
Now I've found this one: https://godotengine.org/qa/4062/freeing-objects-nodes?show=4099#a4099 - which gave me some food for thought...

**Comment by rgutmann** [comment]
I've committed a potential fix for the instability (at least for the hulls). Please check from your side.

**Comment by rgutmann** [comment]
Closing issue as resolved for now.

@KimBrusevold Thank you very much for your input - I've struggled so long with this bug and you've provided exactly the right input to trigger my interest in the right direction! 🥇

**Comment by KimBrusevold** [comment]
Good to hear! I'll check it out! 👍
